TWEAK_NAME = sandcastleclientv3
sandcastleclientv3 = Tweak.xm
sandcastleclientv3_CFLAGS=-I.. -I.
sandcastleclientv3_PRIVATE_FRAMEWORKS = AppSupport


include ../framework/makefiles/common.mk
include ../framework/makefiles/tweak.mk

