TWEAK_NAME = sandstoneclient
sandstoneclient_FILES = Tweak.xm
sandstoneclient_CFLAGS=-I.. -I.
sandstoneclient_PRIVATE_FRAMEWORKS = AppSupport


include ../framework/makefiles/common.mk
include ../framework/makefiles/tweak.mk

